### ISSUE TITLE
Exception when building xpath query

### ISSUE THREAD

**Issue by t8y8** [tableau/document-api-python#46]
I managed to trigger this when downloading workbooks from alpo.

This was done against the HEAD of a local copy of #45 

`Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xml/etree/ElementPath.py", line 263, in iterfind
    selector = _cache[cache_key]
KeyError: (".//metadata-record[@class='column'][local-name='[Today's Date]']", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner.py", line 30, in <module>
    fields = wb_model.datasources[0].fields
  File "/Users/tdoyle/Documents/py/document-api-python/tableaudocumentapi/datasource.py", line 135, in fields
    self._fields = self._get_all_fields()
  File "/Users/tdoyle/Documents/py/document-api-python/tableaudocumentapi/datasource.py", line 141, in _get_all_fields
    return collections.OrderedDict([(k, v) for k, v in column_objects])
  File "/Users/tdoyle/Documents/py/document-api-python/tableaudocumentapi/datasource.py", line 141, in <listcomp>
    return collections.OrderedDict([(k, v) for k, v in column_objects])
  File "/Users/tdoyle/Documents/py/document-api-python/tableaudocumentapi/datasource.py", line 140, in <genexpr>
    for xml in self._datasourceTree.findall('.//column'))
  File "/Users/tdoyle/Documents/py/document-api-python/tableaudocumentapi/datasource.py", line 17, in _mapping_from_xml
    metadata_record = root_xml.find(xpath)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xml/etree/ElementTree.py", line 649, in find
    return self._root.find(path, namespaces)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xml/etree/ElementPath.py", line 298, in find
    return next(iterfind(elem, path, namespaces), None)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xml/etree/ElementPath.py", line 277, in iterfind
    selector.append(ops[token[0]](next, token))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xml/etree/ElementPath.py", line 233, in prepare_predicate
    raise SyntaxError("invalid predicate")
SyntaxError: invalid predicate`

**Comment by t8y8** [comment]
Looks like values can't have quotes for xpath in python.

From the docs: `Selects all elements for which the given attribute has the given value. The value cannot contain quotes.` 

https://docs.python.org/3/library/xml.etree.elementtree.html#supported-xpath-syntax

**Comment by RussTheAerialist** [comment]
Yup, I saw that when I was developing the xpath, but can't believe we don't encode the quote when writing out to the xml.  I'll have to check for single quotes and revert to a more expensive search to get around this.  I'll get this fixed in the morning.  Can you send me the file where you ran into this? I'll turn it into a test case.

**Comment by t8y8** [comment]
I found the twb (I'll send it to you offline until we can scrub it)

We do actually encode it: '[Today&apos;s Date]'

**Comment by RussTheAerialist** [comment]
hah when I looked at that, it didn't include the &amp; code and I was like "How is that even possible?"  Okay so I'll need to add encoding step specifically for &apos;s
